Repository risingwavelabs/risingwave-operator, pull requests merged in 2022-11, with the labels that each got.

#252 feat: support S3-compatible object storages
  .cspell/go.txt
  .cspell/misc.txt
  .github/workflows/ci.yaml
  Makefile
  apis/risingwave/v1alpha1/risingwave_types.go
  apis/risingwave/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/risingwave.risingwavelabs.com_risingwaves.yaml
  config/risingwave-operator-test.yaml
  config/risingwave-operator.yaml
  docs/general/api.md
  examples/risingwave/risingwave-aliyun-oss.yaml
  examples/risingwave/risingwave-etcd-s3.yaml
  examples/risingwave/risingwave-s3-compatible.yaml
  go.mod
  go.sum
  pkg/factory/common.go
  pkg/factory/risingwave_object_factory.go
  pkg/factory/risingwave_object_factory_test.go
  pkg/manager/risingwave_controller_manager_impl.go
  pkg/webhook/risingwave_validating_webhook.go
  pkg/webhook/risingwave_validating_webhook_test.go
Labels: enhancement, mergify/can-merge

#254 fix: fix the label selector JSON path of scale view
  apis/risingwave/v1alpha1/risingwave_scale_view_types.go
  config/crd/bases/risingwave.risingwavelabs.com_risingwavescaleviews.yaml
  config/risingwave-operator-test.yaml
  config/risingwave-operator.yaml
  docs/rfc/0004_component_groups_scale_view.md
Labels: bug, mergify/can-merge, important-soon

#263 ci: add release pipeline
  .github/workflows/release.yml
Labels: mergify/can-merge, ci

#266 ci: fix release pipeline
  .github/workflows/release.yml
Labels: ci

#275 fix: fix codecov
  codecov.yml
Labels: mergify/can-merge

#264 docs: notice about the possible installation failure
  README.md
Labels: documentation, mergify/can-merge

#265 feat: propagate panics properly in concurrent groups/decorators
  pkg/ctrlkit/join.go
  pkg/ctrlkit/join_test.go
  pkg/ctrlkit/parallel.go
  pkg/ctrlkit/parallel_test.go
  pkg/ctrlkit/shared.go
  pkg/ctrlkit/shared_test.go
Labels: mergify/can-merge

#276 ci(Mergify): configuration update
  .mergify.yml
Labels: mergify/can-merge
