Repository risingwavelabs/risingwave-operator, pull requests merged in 2022-12, with the labels that each got.

#283 fix: fix the default value of `-enable-open-kruise` option
  cmd/manager/manager.go
Labels: bug, mergify/can-merge, mergify/high-priority, important-soon

#284 feat: optimize the scale view unlock by watching on only delete events
  pkg/controller/risingwave_controller.go
  pkg/utils/predicates.go
Labels: enhancement, mergify/can-merge

#285 fix: use a pointer for the scaleview.spec.replicas to distinguish bet…
  apis/risingwave/v1alpha1/risingwave_scale_view_types.go
  apis/risingwave/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/risingwave_scale_view_controller_manager_impl_test.go
  pkg/object/scaleview/split.go
  pkg/object/scaleview/split_test.go
  pkg/webhook/risingwave_scale_view_mutating_webhook.go
Labels: enhancement, mergify/can-merge

#288 feat: add the `tolerations` field to the `RisingWaveComponentGroupTemplate`
  apis/risingwave/v1alpha1/risingwave_types.go
  apis/risingwave/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/risingwave.risingwavelabs.com_risingwaves.yaml
  config/risingwave-operator-test.yaml
  config/risingwave-operator.yaml
  docs/general/api.md
  pkg/factory/risingwave_object_factory.go
  pkg/factory/risingwave_object_factory_test.go
Labels: mergify/can-merge

#287 ci: rewrite the e2e test
  .pre-commit-config.yaml
  Makefile
  hack/boilerplate.shell.txt
  test/e2e/README.md
  test/e2e/common/aws.sh
  test/e2e/common/helm.sh
  test/e2e/common/k8s.sh
  test/e2e/common/lib.sh
  test/e2e/common/logging.sh
  test/e2e/common/shell.sh
  test/e2e/e2e.sh
  test/e2e/env
  test/e2e/testenv/kind/config.yaml
  test/e2e/testenv/kind/k8s.sh
  test/e2e/testenv/lib.sh
  test/e2e/testenv/minikube/k8s.sh
  test/e2e/testenv/util/lib.sh
  test/e2e/testenv/util/manifests/network-utils.yaml
  test/e2e/testenv/util/manifests/psql.yaml
  test/e2e/tests/risingwave/manifests/storages/meta-etcd.yaml
  test/e2e/tests/risingwave/manifests/storages/meta-memory-object-memory.yaml
  test/e2e/tests/risingwave/manifests/storages/object-aws-s3.yaml
  test/e2e/tests/risingwave/manifests/storages/object-minio.yaml
  test/e2e/tests/risingwave/tests.sh
  test/e2e/tests/risingwavescaleview/manifests/manual/frontend-empty.yaml
  test/e2e/tests/risingwavescaleview/manifests/manual/frontend-multiple-group.yaml
  test/e2e/tests/risingwavescaleview/tests.sh
  test/e2e/tests/tests.sh
Labels: ci

#290 feat: Support configuring additional labels and annotations
  apis/risingwave/v1alpha1/risingwave_types.go
  apis/risingwave/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/risingwave.risingwavelabs.com_risingwaves.yaml
  config/risingwave-operator-test.yaml
  config/risingwave-operator.yaml
  docs/general/api.md
  pkg/factory/risingwave_object_factory.go
  pkg/factory/risingwave_object_factory_test.go
Labels: mergify/can-merge
