Repository risingwavelabs/risingwave-operator, pull requests merged in 2022-07, with the labels that each got.

#102 fix: PSQL bad link
  README.md
Labels: mergify/can-merge

#103 chore: move some files to legacy dir
  README.md
  docker/Dockerfile
  examples/single-risingwave.yaml
  legacy/scripts/set_minio.sh
  legacy/template/compute-config.yaml
Labels: mergify/can-merge

#104 Update license_check.yml
  .github/workflows/license_check.yml
Labels: mergify/can-merge

#105 RFC: a new design of RisingWave CRD
  .cspell/project-words.txt
  docs/rfc/0003_risingwave_ng.md
  docs/rfc/examples/risingwave_ng.yaml
Labels: mergify/can-merge

#110 docs: fix the readme
  README.md
Labels: mergify/can-merge

#114 docs: fix the readme
  README.md
Labels: documentation, mergify/can-merge

#113 tests: unit tests for object and webhook packages
  .cspell/project-words.txt
  pkg/object/risingwave_manager.go
  pkg/object/risingwave_manager_test.go
  pkg/testutils/testutils.go
  pkg/webhook/risingwave_mutating_webhook_test.go
  pkg/webhook/risingwave_pod_template_validating_webhook_test.go
  pkg/webhook/risingwave_validating_webhook_test.go
Labels: mergify/can-merge

#118 fix: leave the default group out when global replicas is 0; fix updat…
  examples/risingwave-component-only.yaml
  pkg/manager/risingwave_controller_manager_impl.go
  pkg/webhook/risingwave_validating_webhook.go
  pkg/webhook/risingwave_validating_webhook_test.go
Labels: mergify/can-merge

#119 fix(controller): fix the global replicas to check
  pkg/manager/risingwave_controller_manager_impl.go
Labels: bug, mergify/can-merge

#120 feat: support auto-provisioning of service monitors and provide a dashboard for RisingWave
  .cspell/project-words.txt
  README.md
  cmd/manager/manager.go
  config/crd/bases/risingwave.singularity-data.com_risingwavepodtemplates.yaml
  config/crd/bases/risingwave.singularity-data.com_risingwaves.yaml
  config/risingwave-operator-test.yaml
  config/risingwave-operator.yaml
  docs/assets/risingwave-dashboard.png
  examples/legacy/monitoring/prometheus.yaml
  legacy/go.mod
  monitoring/grafana/risingwave-dashboard.json
  monitoring/kube-prometheus-stack.yaml
  pkg/controller/risingwave_controller.go
  pkg/controller/risingwave_controller_test.go
  pkg/factory/risingwave_object_factory.go
  pkg/factory/risingwave_object_factory_test.go
  pkg/manager/risingwave_controller_manager.cm
  pkg/manager/risingwave_controller_manager.go
  pkg/manager/risingwave_controller_manager_impl.go
  pkg/testutils/testutils.go
  pkg/utils/apiextenions.go
Labels: mergify/can-merge

#121 feat: recovery and failover
  apis/risingwave/v1alpha1/risingwave_types.go
  config/crd/bases/risingwave.singularity-data.com_risingwaves.yaml
  config/risingwave-operator-test.yaml
  config/risingwave-operator.yaml
  pkg/controller/risingwave_controller.go
  pkg/controller/risingwave_controller_test.go
  pkg/ctrlkit/common.go
  pkg/ctrlkit/optimize.go
  pkg/ctrlkit/optimize_test.go
  pkg/ctrlkit/shared.go
  pkg/ctrlkit/shared_test.go
  pkg/factory/risingwave_object_factory.go
  pkg/factory/risingwave_object_factory_test.go
  pkg/manager/risingwave_controller_manager.cm
  pkg/manager/risingwave_controller_manager.go
  pkg/manager/risingwave_controller_manager_impl.go
Labels: mergify/can-merge

#124 ci: support code coverage report with codecov
  .cspell/doc.txt
  .github/workflows/ci.yaml
  README.md
  cspell.json
Labels: mergify/can-merge

#125 fix(controller): fix a bug that reconcile fails when ServiceMonitor i…
  pkg/manager/risingwave_controller_manager.cm
  pkg/manager/risingwave_controller_manager.go
  pkg/manager/risingwave_controller_manager_impl.go
Labels: bug, mergify/can-merge

#126 chore: guidance to set up the remote write to AWS Prometheus
  .gitignore
  README.md
  monitoring/prometheus-remote-write-aws.yaml
Labels: documentation, mergify/can-merge

#127 test: rewrite the e2e tests
  .github/workflows/ci.yaml
  .github/workflows/docker_build_operator.yml
  .github/workflows/e2e.yaml
  Makefile
  README.md
  docker/Dockerfile
  docs/dev/development.md
  e2e/check.sql
  e2e/e2e
  e2e/e2e.sh
  e2e/envs/kind-1/config.yaml
  e2e/envs/kind-1/env
  e2e/envs/kind-4/config.yaml
  e2e/envs/kind-4/env
  e2e/envs/minikube/env
  e2e/k8s/kubernetes
  e2e/k8s/network-utils/network-utils.yaml
  e2e/k8s/psql/psql-console.yaml
  e2e/testcases/etcd/risingwave-etcd.yaml
  e2e/testcases/memory/risingwave-memory.yaml
  e2e/testcases/minio/risingwave-minio.yaml
  testing/kind_test.sh
  testing/manager-config.yaml
  testing/rw.yaml
  testing/test-pod.yaml
  testing/utils.sh
Labels: mergify/can-merge

#128 feat(controller): support authentication between meta and etcd
  examples/risingwave-etcd-auth.yaml
  pkg/factory/risingwave_object_factory.go
  pkg/factory/risingwave_object_factory_test.go
Labels: mergify/can-merge, feature

#130 test: add unit tests for controller
  cmd/manager/manager.go
  pkg/controller/risingwave_controller.go
  pkg/controller/risingwave_controller_test.go
Labels: enhancement, mergify/can-merge

#129 test: add unit tests for controller manager
  Makefile
  pkg/factory/risingwave_object_factory.go
  pkg/manager/risingwave_controller_manager_generated.go
  pkg/manager/risingwave_controller_manager_impl.go
  pkg/manager/risingwave_controller_manager_test.go
  pkg/testutils/testutils.go
Labels: enhancement, mergify/can-merge

#132 feat: integrate the grafana loki and promtail into the monitoring stack
  README.md
  docs/assets/grafana-loki-example.png
  monitoring/install.sh
  monitoring/kube-prometheus-stack/grafana-loki-data-source.yaml
  monitoring/kube-prometheus-stack/install.sh
  monitoring/kube-prometheus-stack/kube-prometheus-stack.yaml
  monitoring/kube-prometheus-stack/prometheus-remote-write-aws.yaml
  monitoring/loki-distributed/install.sh
  monitoring/promtail/install.sh
  monitoring/promtail/loki-promtail-clients.yaml
Labels: documentation, mergify/can-merge, feature

#134 feat: set the serviceName for the compute StatefulSet to make each co…
  pkg/controller/risingwave_controller.go
  pkg/factory/risingwave_object_factory.go
Labels: enhancement, mergify/can-merge

#135 fix: e2e-test failed should exit with code 1
  e2e/e2e.sh
Labels: mergify/can-merge

#136 feat: add argument `--client-address` for compute node
  pkg/factory/risingwave_object_factory.go
Labels: mergify/can-merge

#137 test(e2e): fix the test script
  e2e/e2e.sh
Labels: mergify/can-merge

#143 test: fix the flaky controller unit test
  .mergify.yml
  e2e/e2e.sh
  pkg/controller/risingwave_controller_test.go
Labels: mergify/can-merge

#142 chore: add an example for customized config
  examples/risingwave-customize-config.yaml
Labels: mergify/can-merge

#144 chore: improve the mergify rules by checking pending checks
  .mergify.yml
Labels: mergify/can-merge
