Repository risingwavelabs/risingwave-operator, pull requests merged in 2022-08, with the labels that each got.

#150 feat: complete scale, stop and resume commands
  pkg/command/create/config/config.go
  pkg/command/create/config/config_test.go
  pkg/command/create/create.go
  pkg/command/create/create_test.go
  pkg/command/restart/restart.go
  pkg/command/resume/resume.go
  pkg/command/root.go
  pkg/command/scale/scale.go
  pkg/command/stop/stop.go
Labels: mergify/can-merge

#152 feat: set RW_WORKER_THREADS accroding to the resource limits
  pkg/factory/risingwave_object_factory.go
Labels: mergify/can-merge

#156 fix: make sure the pod spec is stable by sorting the slices
  pkg/ctrlkit/join.go
  pkg/ctrlkit/optimize.go
  pkg/factory/common.go
  pkg/factory/risingwave_object_factory.go
  pkg/manager/risingwave_controller_manager_generated.go
  pkg/utils/sort.go
Labels: enhancement, mergify/can-merge

#160 fix & improve: fix the privilege issues by granting get/list/watch on…
  .cspell/project-words.txt
  Makefile
  config/rbac/role.yaml
  config/risingwave-operator-test.yaml
  config/risingwave-operator.yaml
  e2e/e2e
  e2e/e2e.sh
  e2e/envs/local/env
  e2e/testcases/pod-template/risingwave-spot-toleration.yaml
  pkg/controller/risingwave_controller.go
Labels: mergify/can-merge

#158 feat: add an empty mutating webhook for pod template
  config/local/webhook.yaml
  config/risingwave-operator-test.yaml
  config/risingwave-operator.yaml
  config/webhook/manifests.yaml
  examples/risingwave-spot-toleration.yaml
  pkg/webhook/risingwave_pod_template_mutating_webhook.go
  pkg/webhook/risingwave_pod_template_mutating_webhook_test.go
  pkg/webhook/webhook.go
Labels: enhancement, mergify/can-merge

#161 chore: update the image tag to release the v0.1.1
  Makefile
  README.md
Labels: mergify/can-merge

#167 docs: update install command for cert-manager
  README.md
  e2e/e2e.sh
Labels: documentation, mergify/can-merge

#173 ci: improve the pipeline for building images
  .github/workflows/docker_build_operator.yml
  .github/workflows/images.yml
Labels: enhancement, mergify/can-merge, ci

#171 refactor(event): refactor the event hook with a ChainedActionHooks.
  pkg/controller/event_hook.go
  pkg/controller/hooks.go
  pkg/controller/risingwave_controller.go
  pkg/controller/risingwave_controller_test.go
  pkg/ctrlkit/hook.go
  pkg/object/risingwave_manager.go
Labels: enhancement, mergify/can-merge

#174 refactor(event): make most of the events edge-triggered
  pkg/consts/event.go
  pkg/controller/event_hook.go
  pkg/controller/risingwave_controller.go
  pkg/controller/risingwave_controller_test.go
  pkg/controller/risingwave_event_recorder.go
  pkg/event/message_store.go
  pkg/manager/risingwave_controller_manager_impl.go
  pkg/manager/risingwave_controller_manager_test.go
Labels: enhancement, mergify/can-merge

#177 test: fix flaky unit tests by hiding the fake instances and provide …
  pkg/controller/risingwave_controller_test.go
  pkg/factory/risingwave_object_factory_test.go
  pkg/manager/risingwave_controller_manager_test.go
  pkg/object/risingwave_manager_test.go
  pkg/testutils/json.go
  pkg/testutils/testutils.go
  pkg/webhook/risingwave_validating_webhook_test.go
Labels: mergify/can-merge

#175 feat: kubectl plugin
  .github/workflows/e2e.yaml
  Makefile
  cmd/plugin/main.go
  docs/plugin/plugin.md
  docs/rfc/0002_kubectl_rw.md
  e2e/e2e-plugin
  e2e/e2e.sh
  go.mod
  go.sum
  pkg/command/consts.go
  pkg/command/context/client.go
  pkg/command/context/fake.go
  pkg/command/context/interface.go
  pkg/command/context/option.go
  pkg/command/create/config/config.go
  pkg/command/create/config/config_test.go
  pkg/command/create/config/example.toml
  pkg/command/create/config/parser.go
  pkg/command/create/config/parser_test.go
  pkg/command/create/create.go
  pkg/command/create/create_test.go
  pkg/command/delete/delete.go
  pkg/command/deploy/common.go
  pkg/command/deploy/restart.go
  pkg/command/deploy/resume.go
  pkg/command/deploy/scale.go
  pkg/command/deploy/stop.go
  pkg/command/describe/describe.go
  pkg/command/describe/helpers.go
  pkg/command/helper/applier.go
  pkg/command/helper/builder.go
  pkg/command/install/consts.go
  pkg/command/install/downloader.go
  pkg/command/install/install.go
  pkg/command/install/task.go
  pkg/command/install/uninstall.go
  pkg/command/list/list.go
  pkg/command/root.go
  pkg/command/update/update.go
  pkg/command/upgrade/upgrade.go
  pkg/command/util/color.go
  pkg/command/util/consts.go
  pkg/command/util/utils.go
  pkg/command/util/validate.go
  pkg/command/version/version.go
Labels: mergify/can-merge, plugin

#187 chore: mark rfc 0001, 0003 as completed
  docs/rfc/0001_ctrlkit.md
  docs/rfc/0003_risingwave_ng.md
Labels: documentation, mergify/can-merge

#188 style & refactor: misc improvements
  .cspell/project-words.txt
  pkg/command/describe/helpers.go
  pkg/command/helper/applier.go
Labels: enhancement, mergify/can-merge

#192 chore: reorganize the dictionaries used by spell check
  .cspell/doc.txt
  .cspell/go.txt
  .cspell/grafana.txt
  .cspell/k8s.txt
  .cspell/misc.txt
  .cspell/project-words.txt
  .pre-commit-config.yaml
  Makefile
  cspell.json
  pkg/command/deploy/stop.go
Labels: mergify/can-merge

#199 chore: remove legacy example files
  examples/legacy/etcd-service.yaml
  examples/legacy/monitoring/prometheus.yaml
  examples/legacy/risingwave-cloud-load-balancer.yaml
  examples/legacy/s3-risingwave-amd.yaml
  examples/legacy/single-risingwave-arm.yaml
  examples/legacy/single-risingwave.yaml
Labels: mergify/can-merge
