Repository risingwavelabs/risingwave-operator, pull requests merged in 2022-10, with the labels that each got.

#227 refactor: remove the default config
  .cspell/misc.txt
  pkg/factory/risingwave_object_factory.go
  pkg/factory/risingwave_object_factory_test.go
Labels: enhancement, mergify/can-merge

#229 refactor: enhance metric recorders, support metrics recording on the …
  .cspell/go.txt
  pkg/controller/risingwave_controller.go
  pkg/controller/risingwave_controller_test.go
  pkg/controller/risingwave_scale_view_controller.go
  pkg/metrics/controller_metrics_recorder.go
  pkg/metrics/metrics.go
  pkg/metrics/webhook_metrics_recorder.go
  pkg/metrics/webhook_metrics_recorder_test.go
  pkg/utils/types.go
  pkg/webhook/mutating_webhook_metrics_recorder.go
  pkg/webhook/risingwave_mutating_webhook.go
  pkg/webhook/risingwave_mutating_webhook_test.go
  pkg/webhook/risingwave_pod_template_mutating_webhook.go
  pkg/webhook/risingwave_pod_template_validating_webhook.go
  pkg/webhook/risingwave_scale_view_mutating_webhook.go
  pkg/webhook/risingwave_scale_view_validating_webhook.go
  pkg/webhook/risingwave_scale_view_validating_webhook_test.go
  pkg/webhook/risingwave_validating_webhook.go
  pkg/webhook/risingwave_validating_webhook_test.go
  pkg/webhook/validating_webhook_metrics_recorder.go
Labels: enhancement, mergify/can-merge

#234 refactor: validating the resources
  pkg/webhook/risingwave_validating_webhook.go
  pkg/webhook/risingwave_validating_webhook_test.go
Labels: enhancement, mergify/can-merge

#237 docs: move the monitoring docs to a separate file
  README.md
  monitoring/README.md
Labels: documentation, mergify/can-merge

#238 feat: set RUST_BACKTRACE=full in containers of RisingWave by default
  pkg/factory/risingwave_object_factory.go
Labels: enhancement

#240 fix: mark some of the storage fields required
  apis/risingwave/v1alpha1/risingwave_types.go
  config/crd/bases/risingwave.risingwavelabs.com_risingwaves.yaml
  config/risingwave-operator-test.yaml
  config/risingwave-operator.yaml
Labels: enhancement

#241 fix: mount config file for frontend pods
  pkg/factory/risingwave_object_factory.go
Labels: bug

#245 chore(plugin): update the default operator version to v0.2.2
  pkg/command/install/version/verison.go
Labels: enhancement, mergify/can-merge
