Repository risingwavelabs/risingwave-operator, pull requests merged in 2022-09, with the labels that each got.

#202 ci: fix the semver tag
  .github/workflows/images.yml
Labels: mergify/can-merge, ci

#203 chore: update readme for release
  README.md
Labels: documentation, mergify/can-merge

#204 docs(rfc): RFC-0004 expose scale subresource with `RisingWaveScaleView`
  .cspell/k8s.txt
  apis/risingwave/v1alpha1/risingwave_types.go
  docs/rfc/0004_component_groups_scale_view.md
  docs/rfc/images/scale_view_controller_workflow.png
  docs/rfc/images/scale_view_webhooks.png
Labels: documentation

#212 docs: update the development.md
  docs/dev/development.md
Labels: documentation, mergify/can-merge

#213 Run custom operator in local cluster
  docs/dev/development.md
Labels: documentation, mergify/can-merge

#211 ci & build: fix e2e script, bump go to 1.19
  .github/workflows/ci.yaml
  .github/workflows/e2e-plugin.yaml
  .golangci.yaml
  Makefile
  docker/Dockerfile
  docs/dev/development.md
  e2e/e2e-plugin.sh
  e2e/e2e.sh
  e2e/env-utils
  e2e/job/lib
  e2e/util.sh
  go.mod
Labels: ci

#216 fix: add update and watch verbs on ServiceMonitors
  config/crd/bases/risingwave.risingwavelabs.com_risingwaves.yaml
  config/rbac/role.yaml
  config/risingwave-operator-test.yaml
  config/risingwave-operator.yaml
  pkg/controller/risingwave_controller.go
Labels: bug, mergify/can-merge

#217 Docs: prometheus-remote-write-aws.yaml link error
  README.md
Labels: mergify/can-merge

#208 docs: remove the references of the outdated arm64 image
  README.md
  config/manager/configmap.yaml
  config/risingwave-operator-test.yaml
  config/risingwave-operator.yaml
  examples/risingwave-component-groups.yaml
  examples/risingwave-component-only.yaml
  examples/risingwave-customize-config.yaml
  examples/risingwave-etcd-auth.yaml
  examples/risingwave-etcd-minio.yaml
  examples/risingwave-etcd-s3.yaml
  examples/risingwave-in-memory.yaml
  examples/risingwave-privileged.yaml
  examples/risingwave-spot-toleration.yaml
Labels: documentation, mergify/can-merge

#210 feat(controller): support pausing reconciliation with an annotation
  pkg/consts/consts.go
  pkg/controller/risingwave_controller.go
Labels: mergify/can-merge, feature

#220 feat: Support inheriting labels from RisingWave to sub-resources
  pkg/consts/consts.go
  pkg/factory/risingwave_object_factory.go
  pkg/factory/risingwave_object_factory_test.go
Labels: mergify/can-merge, feature

#219 Rewrite Dockerfile to conditional dockerfile
  docker/Dockerfile
Labels: mergify/can-merge

#221 docs: update the link of risingwave-operator manifests
  README.md
Labels: documentation, mergify/can-merge

#214 feat: expose metrics about the operator
  cmd/manager/manager.go
  go.mod
  go.sum
  pkg/command/create/create_test.go
  pkg/controller/risingwave_controller.go
  pkg/controller/risingwave_controller_test.go
  pkg/ctrlkit/loop.go
  pkg/metrics/metrics.go
  pkg/utils/types.go
  pkg/webhook/mutating_webhook_metrics_recorder.go
  pkg/webhook/risingwave_mutating_webhook.go
  pkg/webhook/risingwave_mutating_webhook_test.go
  pkg/webhook/risingwave_pod_template_mutating_webhook.go
  pkg/webhook/risingwave_pod_template_validating_webhook.go
  pkg/webhook/risingwave_validating_webhook.go
  pkg/webhook/risingwave_validating_webhook_test.go
  pkg/webhook/validating_webhook_metrics_recorder.go
  servicemonitor-prometheus-rw-op-system-ns.yaml
Labels: enhancement
