Repository risingwavelabs/risingwave-operator, pull requests merged in 2023-02, with the labels that each got.

#323 chore: update comments and generate manifests
  apis/risingwave/v1alpha1/risingwave_types.go
  config/crd/bases/risingwave.risingwavelabs.com_risingwaves.yaml
  config/risingwave-operator-test.yaml
  config/risingwave-operator.yaml
  docs/general/api.md
  pkg/scaleview/scale_view_helper.go
Labels: documentation, mergify/can-merge

#338 feat(chore): install monitoring stack in parallel
  monitoring/install.sh
  test/e2e/e2e.sh
Labels: mergify/can-merge

#340 chore: update to use risingwave v0.1.16
  docs/manifests/risingwave/risingwave-component-groups.yaml
  docs/manifests/risingwave/risingwave-component-only.yaml
  docs/manifests/risingwave/risingwave-customize-config.yaml
  docs/manifests/risingwave/risingwave-etcd-auth.yaml
  docs/manifests/risingwave/risingwave-etcd-minio.yaml
  docs/manifests/risingwave/risingwave-etcd-s3.yaml
  docs/manifests/risingwave/risingwave-in-memory.yaml
  docs/manifests/risingwave/risingwave-privileged.yaml
  docs/manifests/risingwave/risingwave-spot-toleration.yaml
  docs/manifests/risingwavescaleview/sv-example-frontend.yaml
  docs/manifests/risingwavescaleview/sv-spot-compactor.yaml
  e2e/env-utils
  test/e2e/env
  test/e2e/tests/tests.sh
Labels: documentation, mergify/can-merge, ci

#342 feat: expose metrics for frontend nodes
  pkg/factory/risingwave_object_factory.go
Labels: enhancement, mergify/can-merge

#339 chore: bump go toolchain to 1.20
  .golangci.yaml
  build/Dockerfile
  go.mod
Labels: mergify/can-merge

#346 chore: bump dependencies, various fixes
  Makefile
  config/crd/bases/risingwave.risingwavelabs.com_risingwavepodtemplates.yaml
  config/crd/bases/risingwave.risingwavelabs.com_risingwaves.yaml
  config/risingwave-operator-test.yaml
  config/risingwave-operator.yaml
  docs/general/api.md
  go.mod
  go.sum
  test/e2e/testenv/lib.sh
  test/e2e/tests/risingwave/tests.sh
Labels: mergify/can-merge

#345 feat: support the connector node
  apis/risingwave/v1alpha1/risingwave_scale_view_types.go
  apis/risingwave/v1alpha1/risingwave_types.go
  apis/risingwave/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/risingwave.risingwavelabs.com_risingwaves.yaml
  config/crd/bases/risingwave.risingwavelabs.com_risingwavescaleviews.yaml
  config/risingwave-operator-test.yaml
  config/risingwave-operator.yaml
  docs/general/api.md
  docs/manifests/risingwave/risingwave-component-groups.yaml
  pkg/command/create/config/config.go
  pkg/command/create/config/example.toml
  pkg/command/create/config/parser.go
  pkg/command/create/create.go
  pkg/command/deploy/common.go
  pkg/command/deploy/resume.go
  pkg/command/deploy/scale.go
  pkg/command/deploy/stop.go
  pkg/command/describe/helpers.go
  pkg/command/update/update.go
  pkg/command/update/update_test.go
  pkg/command/upgrade/upgrade.go
  pkg/command/util/consts.go
  pkg/command/util/convert.go
  pkg/command/util/fake.go
  pkg/consts/consts.go
  pkg/controller/risingwave_controller.go
  pkg/controller/risingwave_controller_test.go
  pkg/factory/risingwave_object_factory.go
  pkg/factory/risingwave_object_factory_test.go
  pkg/manager/risingwave_controller_manager.cm
  pkg/manager/risingwave_controller_manager_generated.go
  pkg/manager/risingwave_controller_manager_impl.go
  pkg/manager/risingwave_scale_view_controller_manager_impl.go
  pkg/scaleview/scale_view_helper.go
  pkg/scaleview/scale_view_helper_test.go
  pkg/testutils/testutils.go
  pkg/webhook/risingwave_mutating_webhook.go
  pkg/webhook/risingwave_mutating_webhook_test.go
  pkg/webhook/risingwave_validating_webhook.go
  pkg/webhook/risingwave_validating_webhook_test.go
Labels: mergify/can-merge, feature

#355 docs: add connector node doc
  config/crd/bases/risingwave.risingwavelabs.com_risingwaves.yaml
  config/risingwave-operator-test.yaml
  config/risingwave-operator.yaml
Labels: documentation, mergify/can-merge

#356 test: add e2e test for connector
  test/e2e/e2e.sh
  test/e2e/tests/risingwave/manifests/connector/connector-test.yaml
  test/e2e/tests/risingwave/tests.sh
  test/e2e/tests/tests.sh
Labels: mergify/can-merge

#358 fix: setup meta env
  pkg/factory/risingwave_object_factory.go
Labels: mergify/can-merge

#350 feat: show version in status
  apis/risingwave/v1alpha1/risingwave_types.go
  config/crd/bases/risingwave.risingwavelabs.com_risingwaves.yaml
  pkg/command/describe/helpers.go
  pkg/manager/risingwave_controller_manager_impl.go
  pkg/utils/common.go
  pkg/utils/common_test.go
Labels: enhancement, mergify/can-merge

#361 doc: add version doc
  config/risingwave-operator-test.yaml
  config/risingwave-operator.yaml
  docs/general/api.md
Labels: documentation, mergify/can-merge

#354 feat: add a script for installation
  hack/scripts/install.sh
Labels: mergify/can-merge

#365 refactor: correct component log
  pkg/manager/risingwave_controller_manager_impl.go
Labels: mergify/can-merge

#366 fix: reconciliation errors after an upgrade
  apis/risingwave/v1alpha1/risingwave_types.go
  config/crd/bases/risingwave.risingwavelabs.com_risingwaves.yaml
  config/risingwave-operator-test.yaml
  config/risingwave-operator.yaml
  pkg/factory/risingwave_object_factory.go
Labels: enhancement, mergify/can-merge
