Repository risingwavelabs/risingwave-operator, pull requests merged in 2023-10, with the labels that each got.

#512 chore: update README.md
  README.md
Labels: documentation

#515 chore: fix resource limit
  docs/manifests/risingwave/risingwave-aliyun-oss.yaml
  docs/manifests/risingwave/risingwave-azure.yaml
  docs/manifests/risingwave/risingwave-customize-config.yaml
  docs/manifests/risingwave/risingwave-etcd-auth.yaml
  docs/manifests/risingwave/risingwave-etcd-hdfs.yaml
  docs/manifests/risingwave/risingwave-etcd-local-disk.yaml
  docs/manifests/risingwave/risingwave-etcd-minio.yaml
  docs/manifests/risingwave/risingwave-etcd-s3.yaml
  docs/manifests/risingwave/risingwave-gcs.yaml
  docs/manifests/risingwave/risingwave-hdfs.yaml
  docs/manifests/risingwave/risingwave-in-memory.yaml
  docs/manifests/risingwave/risingwave-s3-compatible.yaml
  docs/manifests/stable/memory/risingwave.yaml
  docs/manifests/stable/persistent/minio/risingwave.yaml
  docs/manifests/stable/persistent/s3/risingwave.yaml
Labels: documentation

#517 ci: update the manifest test
  test/e2e/manifests/tests.sh
Labels: ci

#532 docs: add emptydir for heap profiling
  docs/manifests/risingwave/risingwave-aliyun-oss.yaml
  docs/manifests/risingwave/risingwave-customize-config.yaml
  docs/manifests/risingwave/risingwave-etcd-auth.yaml
  docs/manifests/risingwave/risingwave-etcd-azure.yaml
  docs/manifests/risingwave/risingwave-etcd-hdfs.yaml
  docs/manifests/risingwave/risingwave-etcd-minio.yaml
  docs/manifests/risingwave/risingwave-etcd-s3.yaml
  docs/manifests/risingwave/risingwave-gcs.yaml
  docs/manifests/risingwave/risingwave-hdfs.yaml
  docs/manifests/risingwave/risingwave-s3-compatible.yaml
  docs/manifests/stable/persistent/minio/risingwave.yaml
  docs/manifests/stable/persistent/s3/risingwave.yaml
Labels: documentation

#519 feat: support standalone mode
  apis/risingwave/v1alpha1/risingwave_standalone_mode.go
  apis/risingwave/v1alpha1/risingwave_types.go
  apis/risingwave/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/risingwave.risingwavelabs.com_risingwaves.yaml
  config/risingwave-operator-test.yaml
  config/risingwave-operator.yaml
  docs/general/api.md
  docs/manifests/risingwave/risingwave-standalone.yaml
  pkg/consts/consts.go
  pkg/controller/risingwave_controller.go
  pkg/factory/risingwave_object_factory.go
  pkg/factory/risingwave_object_factory_common_test.go
  pkg/manager/risingwave_controller_manager.cm
  pkg/manager/risingwave_controller_manager_generated.go
  pkg/manager/risingwave_controller_manager_impl.go
  pkg/manager/risingwave_scale_view_controller_manager_impl.go
  pkg/object/risingwave_manager.go
  pkg/scaleview/scale_view_helper.go
Labels: feature

#533 feat: accelerate upgrade of compute sts with an external policy
  cmd/manager/manager.go
  pkg/controller/risingwave_compute_sts_update_strategy.go
  pkg/utils/common.go
Labels: feature
