Repository risingwavelabs/risingwave-operator, pull requests merged in 2023-03, with the labels that each got.

#371 feat: support hdfs object storages
  apis/risingwave/v1alpha1/risingwave_types.go
  apis/risingwave/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/risingwave.risingwavelabs.com_risingwaves.yaml
  config/risingwave-operator-test.yaml
  config/risingwave-operator.yaml
  docs/general/api.md
  docs/manifests/risingwave/risingwave-hdfs.yaml
  hack/cspell/dicts/misc.txt
  pkg/factory/risingwave_object_factory.go
  pkg/factory/risingwave_object_factory_test.go
  pkg/manager/risingwave_controller_manager_impl.go
  pkg/webhook/risingwave_validating_webhook.go
  pkg/webhook/risingwave_validating_webhook_test.go
Labels: mergify/can-merge

#364 feat: enhance the group template with env, envFrom, and affinity
  Makefile
  apis/risingwave/v1alpha1/risingwave_types.go
  apis/risingwave/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/risingwave.risingwavelabs.com_risingwaves.yaml
  config/risingwave-operator-test.yaml
  config/risingwave-operator.yaml
  docs/general/api.md
  hack/cspell/dicts/misc.txt
  pkg/factory/common.go
  pkg/factory/risingwave_object_factory.go
  pkg/factory/risingwave_object_factory_test.go
  pkg/object/risingwave_manager.go
  pkg/webhook/risingwave_validating_webhook_test.go
Labels: enhancement, mergify/can-merge

#374 feat: add JAVA_OPTS
  pkg/consts/consts.go
  pkg/factory/risingwave_object_factory.go
  pkg/webhook/risingwave_validating_webhook.go
Labels: enhancement, mergify/can-merge

#375 fix: use new arguments
  Makefile
  README.md
  docs/dev/rampup_example.md
  docs/manifests/risingwave/risingwave-aliyun-oss.yaml
  docs/manifests/risingwave/risingwave-component-groups.yaml
  docs/manifests/risingwave/risingwave-component-only.yaml
  docs/manifests/risingwave/risingwave-customize-config.yaml
  docs/manifests/risingwave/risingwave-etcd-auth.yaml
  docs/manifests/risingwave/risingwave-etcd-minio.yaml
  docs/manifests/risingwave/risingwave-etcd-s3.yaml
  docs/manifests/risingwave/risingwave-hdfs.yaml
  docs/manifests/risingwave/risingwave-in-memory.yaml
  docs/manifests/risingwave/risingwave-privileged.yaml
  docs/manifests/risingwave/risingwave-s3-compatible.yaml
  docs/manifests/risingwave/risingwave-spot-toleration.yaml
  docs/manifests/risingwavescaleview/sv-example-frontend.yaml
  docs/manifests/risingwavescaleview/sv-spot-compactor.yaml
  e2e/env-utils
  hack/scripts/install.sh
  pkg/factory/risingwave_object_factory.go
  pkg/factory/risingwave_object_factory_test.go
  pkg/utils/common_test.go
  test/e2e/e2e.sh
  test/e2e/env
  test/e2e/testenv/lib.sh
  test/e2e/tests/risingwave/manifests/connector/connector-test.yaml
  test/e2e/tests/risingwave/manifests/multi-meta/multi-meta.yaml
  test/e2e/tests/tests.sh
Labels: enhancement, mergify/can-merge, breaking-change

#352 feat: add `risingwave/meta-role` label to meta pods
  Makefile
  cmd/manager/manager.go
  config/rbac/role.yaml
  config/risingwave-operator-test.yaml
  config/risingwave-operator.yaml
  go.mod
  go.sum
  hack/cspell/dicts/misc.txt
  pkg/consts/consts.go
  pkg/controller/meta_pod_role_labeler.go
  pkg/controller/proto/common.pb.go
  pkg/controller/proto/common.proto
  pkg/controller/proto/meta.pb.go
  pkg/controller/proto/meta.proto
  pkg/controller/proto/meta_grpc.pb.go
  pkg/utils/common.go
Labels: mergify/can-merge, feature

#370 refactor: optimize the unit tests of the `factory` package
  pkg/factory/risingwave_object_factory_common_test.go
  pkg/factory/risingwave_object_factory_predicate_test.go
  pkg/factory/risingwave_object_factory_test.go
  pkg/factory/risingwave_object_factory_testcases_test.go
Labels: enhancement, mergify/can-merge

#376 fix: pass the credentials for accessing the state store to compute an…
  pkg/factory/risingwave_object_factory.go
Labels: bug, mergify/can-merge

#380 fix: update the resources of manager to avoid OOM
  config/manager/manager.yaml
  config/risingwave-operator-test.yaml
  config/risingwave-operator.yaml
Labels: mergify/can-merge

#383 chore(metrics): drop `batch.* & stream_exchage.*` metrics for risingwave
  pkg/factory/risingwave_object_factory.go
Labels: mergify/can-merge

#388 fix: pass total available memory to the compute process
  pkg/factory/risingwave_object_factory.go
  pkg/factory/risingwave_object_factory_testcases_test.go
Labels: enhancement

#387 feat: resolve meta conflict
  Makefile
  build/Dockerfile
  cmd/manager/manager.go
  pkg/consts/consts.go
  pkg/controller/risingwave_controller.go
  pkg/factory/risingwave_object_factory.go
  pkg/factory/risingwave_object_factory_common_test.go
  pkg/factory/risingwave_object_factory_predicate_test.go
  pkg/factory/risingwave_object_factory_test.go
  pkg/features/feature_manager.go
  pkg/manager/risingwave_controller_manager_impl.go
  pkg/manager/risingwave_controller_manager_test.go
Labels: mergify/can-merge
