Repository risingwavelabs/risingwave-operator, pull requests merged in 2023-01, with the labels that each got.

#300 chore: fix e2e scripts to pass shellcheck
  test/e2e/common/shell.sh
  test/e2e/e2e.sh
Labels: mergify/can-merge

#303 chore: cleanup the root dir
  .github/workflows/images.yml
  Makefile
  README.md
  build/Dockerfile
  codecov.yml
  docs/manifests/psql/psql-console.yaml
  docs/manifests/risingwave/risingwave-aliyun-oss.yaml
  docs/manifests/risingwave/risingwave-component-groups.yaml
  docs/manifests/risingwave/risingwave-component-only.yaml
  docs/manifests/risingwave/risingwave-customize-config.yaml
  docs/manifests/risingwave/risingwave-etcd-auth.yaml
  docs/manifests/risingwave/risingwave-etcd-minio.yaml
  docs/manifests/risingwave/risingwave-etcd-s3.yaml
  docs/manifests/risingwave/risingwave-in-memory.yaml
  docs/manifests/risingwave/risingwave-privileged.yaml
  docs/manifests/risingwave/risingwave-s3-compatible.yaml
  docs/manifests/risingwave/risingwave-spot-toleration.yaml
  docs/manifests/risingwavescaleview/sv-example-frontend.yaml
  docs/manifests/risingwavescaleview/sv-spot-compactor.yaml
  docs/rfc/0003_risingwave_ng.md
  docs/rfc/manifests/risingwave_ng.yaml
  hack/cspell/cspell.json
  hack/cspell/dicts/go.txt
  hack/cspell/dicts/k8s.txt
  hack/cspell/dicts/makefile.txt
  hack/cspell/dicts/misc.txt
  hack/cspell/dicts/project-words.txt
  hack/docs/config.json
  hack/docs/templates/members.tpl
  hack/docs/templates/pkg.tpl
  hack/docs/templates/type.tpl
  pkg/command/context/client.go
  pkg/command/context/option.go
Labels: mergify/can-merge

#297 feat: add the `podsMeta` to the `RisingWaveComponentGroupTemplate`
  apis/risingwave/v1alpha1/risingwave_types.go
  apis/risingwave/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/risingwave.risingwavelabs.com_risingwaves.yaml
  config/risingwave-operator-test.yaml
  config/risingwave-operator.yaml
  docs/general/api.md
  pkg/factory/risingwave_object_factory.go
  pkg/factory/risingwave_object_factory_test.go
  pkg/webhook/risingwave_validating_webhook.go
  pkg/webhook/risingwave_validating_webhook_test.go
Labels: mergify/can-merge

#305 feat: support --parallelism and --total-memory-bytes for the compute …
  apis/risingwave/v1alpha1/zz_generated.deepcopy.go
  docs/manifests/risingwave/risingwave-component-groups.yaml
  docs/manifests/risingwave/risingwave-component-only.yaml
  docs/manifests/risingwave/risingwave-customize-config.yaml
  docs/manifests/risingwave/risingwave-etcd-auth.yaml
  docs/manifests/risingwave/risingwave-etcd-minio.yaml
  docs/manifests/risingwave/risingwave-etcd-s3.yaml
  docs/manifests/risingwave/risingwave-in-memory.yaml
  docs/manifests/risingwave/risingwave-privileged.yaml
  docs/manifests/risingwave/risingwave-spot-toleration.yaml
  docs/manifests/risingwavescaleview/sv-example-frontend.yaml
  docs/manifests/risingwavescaleview/sv-spot-compactor.yaml
  e2e/env-utils
  pkg/factory/risingwave_object_factory.go
  pkg/factory/risingwave_object_factory_test.go
  test/e2e/env
  test/e2e/tests/tests.sh
Labels: enhancement, mergify/can-merge

#307 fix: listen on 0.0.0.0 for frontend and compactor
  pkg/factory/risingwave_object_factory.go
Labels: enhancement, mergify/can-merge

#310 ci: support build images to DockerHub
  .github/workflows/images.yml
Labels: ci

#314 ci: try to fix the image workflow
  .github/workflows/images.yml
Labels: ci

#316 ci: update golangci lint config
  .golangci.yaml
  apis/risingwave/v1alpha1/risingwave_pod_template_types.go
  apis/risingwave/v1alpha1/risingwave_scale_view_types.go
  apis/risingwave/v1alpha1/risingwave_types.go
  cmd/manager/manager.go
  config/crd/bases/risingwave.risingwavelabs.com_risingwavepodtemplates.yaml
  config/crd/bases/risingwave.risingwavelabs.com_risingwaves.yaml
  config/crd/bases/risingwave.risingwavelabs.com_risingwavescaleviews.yaml
  pkg/command/context/dummy.go
  pkg/consts/consts.go
  pkg/consts/event.go
  pkg/controller/risingwave_controller.go
  pkg/controller/risingwave_controller_test.go
  pkg/controller/risingwave_scale_view_controller.go
  pkg/ctrlkit/exit.go
  pkg/ctrlkit/internal/action.go
  pkg/ctrlkit/internal/decorator.go
  pkg/ctrlkit/join.go
  pkg/ctrlkit/new.go
  pkg/ctrlkit/nop.go
  pkg/ctrlkit/optimize.go
  pkg/ctrlkit/parallel.go
  pkg/ctrlkit/retry.go
  pkg/ctrlkit/sequential.go
  pkg/ctrlkit/shared.go
  pkg/ctrlkit/timeout.go
  pkg/ctrlkit/utils.go
  pkg/event/message_store.go
  pkg/factory/risingwave_object_factory.go
  pkg/factory/risingwave_object_factory_test.go
  pkg/features/feature_manager.go
  pkg/features/feature_manager_test.go
  pkg/manager/risingwave_controller_manager_impl.go
  pkg/manager/risingwave_scale_view_controller_manager_impl.go
  pkg/metrics/controller_metrics_recorder.go
  pkg/metrics/metrics.go
  pkg/metrics/webhook_metrics_recorder.go
  pkg/object/risingwave_manager.go
  pkg/object/scale_view_lock_manager.go
  pkg/object/scaleview/split.go
  pkg/object/scaleview/split_test.go
  pkg/scaleview/scale_view_helper.go
  pkg/testutils/json.go
  pkg/testutils/testutils.go
  pkg/utils/apiextenions.go
  pkg/utils/apps.go
  pkg/utils/common.go
  pkg/utils/core.go
  pkg/utils/sort.go
  pkg/webhook/risingwave_mutating_webhook.go
  pkg/webhook/risingwave_pod_template_mutating_webhook.go
  pkg/webhook/risingwave_pod_template_validating_webhook.go
  pkg/webhook/risingwave_scale_view_mutating_webhook.go
  pkg/webhook/risingwave_scale_view_validating_webhook.go
  pkg/webhook/risingwave_validating_webhook.go
Labels: mergify/can-merge, ci

#312 feat: use StatefulSet to manage meta Pods
  pkg/controller/risingwave_controller.go
  pkg/controller/risingwave_controller_test.go
  pkg/factory/risingwave_object_factory.go
  pkg/factory/risingwave_object_factory_test.go
  pkg/manager/risingwave_controller_manager.cm
  pkg/manager/risingwave_controller_manager_generated.go
  pkg/manager/risingwave_controller_manager_impl.go
  pkg/manager/risingwave_controller_manager_test.go
Labels: mergify/can-merge, feature, breaking-change

#321 feat: provide an option to enable/disable the default ServiceMonitor
  apis/risingwave/v1alpha1/risingwave_types.go
  apis/risingwave/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/risingwave.risingwavelabs.com_risingwaves.yaml
  config/risingwave-operator-test.yaml
  config/risingwave-operator.yaml
  docs/general/api.md
  pkg/controller/risingwave_controller.go
Labels: enhancement

#320 feat: shorten the probe initial delay time to improve scaling experience
  pkg/factory/risingwave_object_factory.go
Labels: enhancement, mergify/can-merge

#326 fix: use ceil instead of floor
  pkg/factory/risingwave_object_factory.go
Labels: bug

#332 ci(Mergify): configuration update
  .mergify.yml
Labels: mergify/can-merge, ci

#325 docs: use GKE instead of GCP
  README.md
Labels: documentation
